version: '3.8'

services:
  db:
    image: mysql:5.7.40
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeit
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db